mysql:
  ports:
    - "3318:3306"
  env_file:
    - ./conf/env_file/stage/env
prestashop16:
  container_name: hipay-enterprise-shop-ps16-stage
  dockerfile: ./conf/docker/Dockerfile16
  build: .
  ports:
    - "8086:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/stage/env
    - ./conf/env_file/stage/env16
prestashop17:
  container_name: hipay-enterprise-shop-ps17-stage
  dockerfile: ./conf/docker/Dockerfile17
  build: .
  ports:
    - "8087:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/stage/env
    - ./conf/env_file/stage/env17
smtp:
  ports:
    - "1018:80"

