prestashop:
  container_name: hipay-professional-shop-ps17-dev
  dockerfile: ./conf/docker/Dockerfile17
  build: .
  ports:
    - "8087:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/development/env
    - ./conf/env_file/development/env17
  volumes:
    - ./web17:/var/www/html
    - ./src/hipay_professional:/var/www/html/modules/hipay_professional
