version: "3.3"

services:
  web17:
    container_name: prestashop_web_17
    image: gcr.io/pi-dev-sandbox/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web17:${CI_COMMIT_REF_SLUG}
    build:
      context: .
      dockerfile: ./bin/docker/images/prestashop/Dockerfile17
    depends_on:
      - database
    env_file:
      - ./bin/docker/conf/test/env
      - ./bin/docker/conf/test/env17
    ports:
      - "8077:80"

  web16:
    container_name: prestashop_web_17_16
    image: gcr.io/pi-dev-sandbox/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web16:${CI_COMMIT_REF_SLUG}
    build:
      context: .
      dockerfile: ./bin/docker/images/prestashop/Dockerfile16
    depends_on:
      - database
    env_file:
      - ./bin/docker/conf/test/env
      - ./bin/docker/conf/test/env16
    ports:
      - "8076:80"

  database:
    image: mysql:5.7
    container_name: prestashop_database
    env_file:
      - ./bin/docker/conf/test/env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
