database:
  image: mysql:5.7
  ports:
    - "3317:3306"
  env_file:
    - ./bin/docker/conf/development/env
  mem_limit: 500M

smtp:
  image: schickling/mailcatcher
  ports:
    - "1017:1080"
  mem_limit: 256M

prestashop16:
  container_name: hipay-professional-shop-ps16
  dockerfile: ./bin/docker/images/prestashop/Dockerfile16
  build: .
  ports:
    - "8076:80"
  links:
    - smtp
    - database
  env_file:
    - ./bin/docker/conf/development/env
    - ./bin/docker/conf/development/env16
  volumes:
    - ./web16:/var/www/html
    - ./src/hipay_professional:/var/www/html/modules/hipay_professional
  mem_limit: 500M

prestashop17:
 container_name: hipay-professional-shop-ps17
 dockerfile: ./bin/docker/images/prestashop/Dockerfile17
 build: .
 ports:
   - "8077:80"
 links:
   - smtp
   - database
 env_file:
   - ./bin/docker/conf/development/env
   - ./bin/docker/conf/development/env17
 volumes:
   - ./web17:/var/www/html
   - ./src/hipay_professional:/var/www/html/modules/hipay_professional
 mem_limit: 500M
